#!/usr/bin/env python3
"""Export a ControlBot profile.yaml from CMMC program data inheritance.

Derives inherited NIST SP 800-53 controls from assessment objectives marked
inherited (not shared) in program-data.yaml, using references/data/
800-53-crosswalk.json. Writes a starter .controlbot/profile.yaml for IaC
repos alongside the compliance program repo.

Usage (from repo root):
    python3 scripts/export_controlbot_profile.py program-data.yaml -o .controlbot/profile.yaml
    python3 scripts/export_controlbot_profile.py program-data.yaml --stdout
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from crosswalk_lib import load_crosswalk  # noqa: E402
from merge_findings import load_program  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = REPO_ROOT / "templates" / "controlbot-profile.sample.yaml"


def _controls_for_requirement(cmmc_id: str, crosswalk: dict[str, Any]) -> list[str]:
    for row in crosswalk.get("requirements") or []:
        if row.get("cmmc_id") == cmmc_id:
            return list(row.get("controls_800_53_rev4") or [])
    return []


def _parse_crm_controls(crm_ref: str) -> list[str]:
    import re

    return re.findall(r"[A-Z]{2}-\d+(?:\(\d+\))?", crm_ref or "")


def collect_inherited_controls(program: dict, crosswalk: dict[str, Any]) -> list[str]:
    controls: set[str] = set()
    reqs = program.get("requirements") or {}
    for req_id, entry in reqs.items():
        if not isinstance(entry, dict):
            continue
        for obj in (entry.get("objectives") or {}).values():
            if not isinstance(obj, dict):
                continue
            if obj.get("conformity") != "inherited":
                continue
            inheritance = obj.get("inheritance") or {}
            if inheritance.get("type") not in (None, "inherited"):
                continue
            controls.update(_controls_for_requirement(req_id, crosswalk))
            controls.update(_parse_crm_controls(str(inheritance.get("crm_ref") or "")))
    return sorted(controls)


def render_profile(
    program: dict,
    inherited: list[str],
    *,
    baseline: str = "fedramp-moderate",
    bot_name: str = "ControlBot",
) -> str:
    org = (program.get("organization") or {}).get("name") or "organization"
    lines = [
        "# Generated by scripts/export_controlbot_profile.py",
        f"# Organization: {org}",
        "# Populate inherited_controls from CRM rows marked provider-responsible.",
        "# Re-run after inheritance updates in program-data.yaml.",
        "",
        f"baseline: {baseline}",
        "inherited_controls:",
    ]
    if inherited:
        for ctrl in inherited:
            lines.append(f"  - {ctrl}")
    else:
        lines.append("  []  # add CRM-inherited controls, e.g. PE-1, PE-2")
    lines.extend(
        [
            "block_on_severity:",
            "  - HIGH",
            "  - CRITICAL",
            "inline_comments: true",
            f"bot_name: {bot_name}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description="Export ControlBot profile from program data inheritance")
    ap.add_argument("program_data", type=Path)
    ap.add_argument("-o", "--out", type=Path, help="output profile path (default: stdout)")
    ap.add_argument("--stdout", action="store_true", help="write YAML to stdout")
    ap.add_argument("--baseline", default="fedramp-moderate")
    args = ap.parse_args()

    program = load_program(args.program_data)
    crosswalk = load_crosswalk()
    inherited = collect_inherited_controls(program, crosswalk)
    text = render_profile(program, inherited, baseline=args.baseline)

    if args.stdout or not args.out:
        print(text, end="")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({len(inherited)} inherited controls)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
